workspace/www/Assignment2/Assignment2/app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('job/showAll', array('as' => 'job.showAll', 'uses' => 'JobController@showAll'));
Route::get('user/showAllEmployers', array('as' => 'user.showAllEmployers', 'uses' => 'UserController@showAllEmployers'));
Route::get('user/documentation', array('as' => 'user.documentation', 'uses' => 'UserController@documentation'));

Route::resource('user', 'UserController');
Route::resource('job', 'JobController');

Route::get('/', function()
{
	return View::make('users.index');
});


/*
Route::get('about', function()
{
	return View::make('pages.about');
});
Route::get('projects', function()
{
	return View::make('pages.projects');
});
Route::get('contact', function()
{
	return View::make('pages.contact');
});*/

workspace/www/Assignment2/Assignment2/app/views/layout.blade.php
<html>
  <head>
    <title>@yield('title')</title>

    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">

    <!-- Optional theme -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">

    <!-- Latest compiled and minified JavaScript -->
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>

  </head>
  <body>
    <p>Created by Anthony Lee, s2836454</p>
    <h1> Job Website </h1>

    <div>
      <div class="col-md-2">
        <div class=list-group-item>{{ link_to_route('user.index', 'User Home') }}</div>
        <div class=list-group-item>{{ link_to_route('job.showAll', 'List All Jobs') }}</div>
        <div class=list-group-item>{{ link_to_route('user.showAllEmployers', 'List All Employers') }}</div>
        <div class=list-group-item>{{ link_to_route('user.documentation', 'Documentation') }}</div>
        <!--@yield('links')-->
      </div>
      <div class="col-md-10">@yield('content')</div>
    </div>


  </body>
</html>