workspace/www/Assignment2/Assignment2/app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('job/showAll', array('as' => 'job.showAll', 'uses' => 'JobController@showAll'));
Route::get('user/showAllEmployers', array('as' => 'user.showAllEmployers', 'uses' => 'UserController@showAllEmployers'));
Route::get('user/documentation', array('as' => 'user.documentation', 'uses' => 'UserController@documentation'));

Route::resource('user', 'UserController');
Route::resource('job', 'JobController');

Route::get('/', function()
{
	return View::make('users.index');
});


/*
Route::get('about', function()
{
	return View::make('pages.about');
});
Route::get('projects', function()
{
	return View::make('pages.projects');
});
Route::get('contact', function()
{
	return View::make('pages.contact');
});*/

workspace/www/Assignment2/Assignment2/app/models/Job.php
<?php
class Job extends Eloquent {}

workspace/www/Assignment2/Assignment2/app/controllers/JobController.php
<?php

class JobController extends \BaseController {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		//
	}
  
  /**
  * Returns a list of all jobs
  */
  public function showAll()
  {
     $jobs = Job::all();
     return View::make('jobs.showAll', compact('jobs'));
  }


	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		//
	}


	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		//
	}


	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$job = Job::find($id);

    $now_date = new DateTime();
    $now_date->setTimestamp(strtotime(date('Y-m-d')));
    $finalDate = new DateTime();
    $finalDate->setTimestamp(strtotime(str_replace('-','/', $job->endingDate)));

    $dateDiff = $now_date->diff($finalDate)->format("%r%a");
    if ($dateDiff < 0) $dateDiff = 0;
    
    return View::make('jobs.show')->with('job', $job)->with('dateDiff', $dateDiff);
    
	}


	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		//
	}


	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		//
	}


	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		//
	}


}

workspace/www/Assignment2/Assignment2/app/views/jobs/show.blade.php
@extends('layout')
@section('title')
Users
@stop
@section('content')
  <table class="table table-striped table-bordered table-condensed">
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Location</th>
      <th>Salary</th>
      <th>Starting Date</th>
      <th>Ending Date</th>
      <th>Days left to Apply</th>
    </tr>  
    <tr>
      <td>{{{ $job->title }}}</td>
      <td>{{{ $job->jobDescription }}}</td>
      <td>{{{ $job->location }}}</td>
      <td>{{{ $job->salary }}}</td>
      <td>{{{ $job->startingDate }}}</td>
      <td>{{{ $job->endingDate }}}</td>
      <td>{{{ $dateDiff  }}}</td>
    </tr>     
@stop
    
    

workspace/www/Assignment2/Assignment2/app/views/jobs/showAll.blade.php
@extends('layout')
@section('title')
Users
@stop
@section('content')
  <table class="table table-striped table-bordered table-condensed">
    <tr>
      <th>Title</th>
      <th>Description</th>
    </tr>
    @foreach ($jobs as $job)
    <tr>
      <td>{{ link_to_route('job.show', $job->title, array($job->id)) }}</td>
      <td>{{{ $job->jobDescription }}}</td>
    </tr>
    @endforeach
@stop
    